project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views
from app.converter.forms import LoginForm
from app.converter.views import UserView, CreditsView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('app.converter.urls')),
    url(r'^login/$', auth_views.login, {'template_name': 'app/login.html', 'authentication_form': LoginForm, 'redirect_authenticated_user': True}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    url(r'^register/', UserView.as_view(), name="register"),
    url(r'^edit/', UserView.as_view(), name="edit"),
    url(r'^credits/', CreditsView.as_view()),
    url(r'^summarizer/', include('app.summarizer.urls')),
    url(r'^translator/', include('app.translator.urls')),
    url(r'^aligner/', include('app.aligner.urls')),
]

summarizer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^', include('apps.convert_app.urls')),
    url(r'^admin/', admin.site.urls),
]

app/translator/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings

from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

from app.converter.models import File
from choices import LANGUAGE_CHOICES
from utils import TranslateFile
import os

class Translated(models.Model):
	file = models.ForeignKey(File, on_delete=models.CASCADE,
							 null=False, blank=False)
	from_language = models.CharField(max_length=20, choices=LANGUAGE_CHOICES, editable=False)
	to_language = models.CharField(max_length=20, choices=LANGUAGE_CHOICES, null=False, blank=False)
	translated_file = models.CharField(max_length=200, editable=False)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def save(self, *args, **kwargs):
		TranslateFile(self)
		super(Translated, self).save()

	@receiver(pre_delete, sender=File)
	def remove_file(sender, *args, **kwargs):
		try:
			file_id = sender.objects.first().id
			translated_file = Translated.objects.get(file_id=file_id).translated_file
			os.remove(os.path.join(settings.MEDIA_ROOT, translated_file))
		except:
			pass

	def __unicode__(self):
		return self.translated_file

app/translator/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from models import Translated
from choices import LANGUAGE_CHOICES
from utils import TranslateFile
import os

class SubmitTranslatedForm(forms.Form):
	file = forms.CharField(widget=forms.HiddenInput())
	to_language = forms.ChoiceField(choices=LANGUAGE_CHOICES, 
								label="Idioma da tradução", 
								widget=forms.Select(attrs={"class" : "form-control input-mg"}))

app/translator/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings

from app.converter.models import File
from app.summarizer.models import Summarized
from choices import LANGUAGE_CHOICES
from models import Translated
from forms import SubmitTranslatedForm

import os

class IndexView(View):
	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated():
			messages.error(request, "Nenhum arquivo foi selecionado!")

		return redirect("/")
		
	def post(self, request, *args, **kwargs):
		method = self.request.POST.get('_method', '').lower()

		file_id = request.POST.get('file', None)
		file = get_object_or_404(File, id=file_id)

		if method == u'translated':
			return self.translate(request, file, *args, **kwargs)
		else:
			form = SubmitTranslatedForm(initial={'file': file_id})
			template = "translator/index.html"

			context = {
				"title": "Tradutor",
				"file": file,
				"form": form
			}
			return render(request, template, context)

	def translate(self, request, file, *args, **kwargs):
		form = SubmitTranslatedForm(request.POST or None)

		if form.is_valid():
			update = Translated.objects.filter(file_id=file.id)

			if update:
				translated = Translated.objects.get(file_id=file.id)
				translated.to_language = request.POST['to_language']
			else:
				translated = Translated(
					file = file,
					to_language = request.POST['to_language']
				)

			# cleaned data
			to_language = form.cleaned_data["to_language"]

			translated.save()

			messages.success(request, "O arquivo " + file.title +
							" foi traduzido com sucesso!")

		template = "translator/index.html"

		context = {
			"title": "Tradutor",
			"file": file,
			"translated": {
				"from_language": dict(LANGUAGE_CHOICES).get(translated.from_language),
				"to_language": dict(LANGUAGE_CHOICES).get(translated.to_language)
			}
		}
		return render(request, template, context)

templates/translator/index.html
{% extends 'app/base.html' %}

{% load staticfiles %}

{% block content %}
	{% if form %}
		<form method="POST" action="/translator/" class="form-horizontal" >
			{% csrf_token %}
			{% for field in form.visible_fields %}
				<div class="form-group">
	    			<label class="control-label lb-lg" for="{{ field.name }}">{{ field.label }}:</label> {{ field }}
	    		</div>
			{% endfor %}
			{% for field in form.hidden_fields %}
				<div style="display:none;">{{ field }}</div>
			{% endfor %}
			<button type="submit" name="_method" value="translated" class="btn btn-primary btn-lg btn-block" title="Traduzir" id="run_app">Traduzir</button>
	{% else %}
		<div class="subtitle-session">
			<h2>Estatísticas da tradução <span class="glyphicon glyphicon-stats"></span></h2>
			<h4>Idiomas: {{ translated.from_language }} <small>(Fonte) </small>
			<span class="glyphicon glyphicon-transfer"> </span>
			{{ translated.to_language }}
			<small>(Alvo)</small></h4>
		</div>
		<form method="POST" action="/aligner/" class="form-horizontal" >
			{% csrf_token %}
			<div style="display:none;"><input type="hidden" name="file" id="id_file" value="{{ file.id }}"/></div>
		<br/>
		<button type="submit" name="_method" value="translated" class="btn btn-primary btn-lg btn-block" title="Alinhador">Avançar</button>
	{% endif %}
	</form>
{% endblock content %}